default_language_version:
  python: python3.13

default_stages: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: code-check
        name: code-check (local)
        entry: make check
        language: system
        pass_filenames: false
      - id: pip-audit-local
        name: pip-audit (local)
        entry: make pip-audit
        language: system
        pass_filenames: false
        verbose: true
      - id: shellcheck
        name: shellcheck (local)
        entry: uv run shellcheck
        language: system
        args: ["--severity=warning"]
        types: [shell]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
        exclude: docker-compose.test.yml|docker-compose.migration.yml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        args: ["--branch=develop", "--branch=dev", "--branch=master", "--branch=main"]
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: v1.50.1
    hooks:
      - id: typos
        args: ["--force-exclude"]

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
      - id: pretty-format-yaml
        name: YAML formatter
        files: (^|/).*\.ya?ml$
        args: ["--autofix", "--indent", "2", "--offset", "2", "--preserve-quotes"]
